// <auto-generated />
using System;
using CIMBTest.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CIMBTest.Migrations
{
    [DbContext(typeof(BaseContext))]
    partial class BaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CIMBTest.Models.UseCase_01", b =>
                {
                    b.Property<string>("jeniskredit")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("kreditno")
                        .HasColumnType("int");

                    b.Property<string>("Active")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tahunBulan01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tahunBulan01Kol")
                        .HasColumnType("int");

                    b.Property<string>("tahunBulan02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tahunBulan02Kol")
                        .HasColumnType("int");

                    b.Property<string>("tahunBulan03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tahunBulan03Kol")
                        .HasColumnType("int");

                    b.Property<string>("tahunBulan04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tahunBulan04Kol")
                        .HasColumnType("int");

                    b.Property<string>("tahunBulan05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tahunBulan05Kol")
                        .HasColumnType("int");

                    b.Property<string>("tahunBulan06")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tahunBulan06Kol")
                        .HasColumnType("int");

                    b.Property<string>("tahunBulan07")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tahunBulan07Kol")
                        .HasColumnType("int");

                    b.Property<string>("tahunBulan08")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tahunBulan08Kol")
                        .HasColumnType("int");

                    b.Property<string>("tahunBulan09")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tahunBulan09Kol")
                        .HasColumnType("int");

                    b.Property<string>("tahunBulan10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tahunBulan10Kol")
                        .HasColumnType("int");

                    b.Property<string>("tahunBulan11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tahunBulan11Kol")
                        .HasColumnType("int");

                    b.Property<string>("tahunBulan12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tahunBulan12Kol")
                        .HasColumnType("int");

                    b.Property<string>("tahunBulan13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tahunBulan13Kol")
                        .HasColumnType("int");

                    b.Property<string>("tahunBulan14")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tahunBulan14Kol")
                        .HasColumnType("int");

                    b.Property<string>("tahunBulan15")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tahunBulan15Kol")
                        .HasColumnType("int");

                    b.Property<string>("tahunBulan16")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tahunBulan16Kol")
                        .HasColumnType("int");

                    b.Property<string>("tahunBulan17")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tahunBulan17Kol")
                        .HasColumnType("int");

                    b.Property<string>("tahunBulan18")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tahunBulan18Kol")
                        .HasColumnType("int");

                    b.Property<string>("tahunBulan19")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tahunBulan19Kol")
                        .HasColumnType("int");

                    b.Property<string>("tahunBulan20")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tahunBulan20Kol")
                        .HasColumnType("int");

                    b.Property<string>("tahunBulan21")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tahunBulan21Kol")
                        .HasColumnType("int");

                    b.Property<string>("tahunBulan22")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tahunBulan22Kol")
                        .HasColumnType("int");

                    b.Property<string>("tahunBulan23")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tahunBulan23Kol")
                        .HasColumnType("int");

                    b.Property<string>("tahunBulan24")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tahunBulan24Kol")
                        .HasColumnType("int");

                    b.Property<int>("tahunbulan01ht")
                        .HasColumnType("int");

                    b.Property<int>("tahunbulan02ht")
                        .HasColumnType("int");

                    b.Property<int>("tahunbulan03ht")
                        .HasColumnType("int");

                    b.Property<int>("tahunbulan04ht")
                        .HasColumnType("int");

                    b.Property<int>("tahunbulan05ht")
                        .HasColumnType("int");

                    b.Property<int>("tahunbulan06ht")
                        .HasColumnType("int");

                    b.Property<int>("tahunbulan07ht")
                        .HasColumnType("int");

                    b.Property<int>("tahunbulan08ht")
                        .HasColumnType("int");

                    b.Property<int>("tahunbulan09ht")
                        .HasColumnType("int");

                    b.Property<int>("tahunbulan10ht")
                        .HasColumnType("int");

                    b.Property<int>("tahunbulan11ht")
                        .HasColumnType("int");

                    b.Property<int>("tahunbulan12ht")
                        .HasColumnType("int");

                    b.Property<int>("tahunbulan13ht")
                        .HasColumnType("int");

                    b.Property<int>("tahunbulan14ht")
                        .HasColumnType("int");

                    b.Property<int>("tahunbulan15ht")
                        .HasColumnType("int");

                    b.Property<int>("tahunbulan16ht")
                        .HasColumnType("int");

                    b.Property<int>("tahunbulan17ht")
                        .HasColumnType("int");

                    b.Property<int>("tahunbulan18ht")
                        .HasColumnType("int");

                    b.Property<int>("tahunbulan19ht")
                        .HasColumnType("int");

                    b.Property<int>("tahunbulan20ht")
                        .HasColumnType("int");

                    b.Property<int>("tahunbulan21ht")
                        .HasColumnType("int");

                    b.Property<int>("tahunbulan22ht")
                        .HasColumnType("int");

                    b.Property<int>("tahunbulan23ht")
                        .HasColumnType("int");

                    b.Property<int>("tahunbulan24ht")
                        .HasColumnType("int");

                    b.HasKey("jeniskredit", "kreditno");

                    b.ToTable("Table_01");

                    b.HasData(
                        new
                        {
                            jeniskredit = "X-30",
                            kreditno = 1,
                            Active = "Y",
                            tahunBulan01 = "202207",
                            tahunBulan01Kol = 1,
                            tahunBulan02 = "202208",
                            tahunBulan02Kol = 1,
                            tahunBulan03 = "202209",
                            tahunBulan03Kol = 1,
                            tahunBulan04 = "202210",
                            tahunBulan04Kol = 1,
                            tahunBulan05 = "202211",
                            tahunBulan05Kol = 1,
                            tahunBulan06 = "202212",
                            tahunBulan06Kol = 2,
                            tahunBulan07 = "202301",
                            tahunBulan07Kol = 2,
                            tahunBulan08 = "202302",
                            tahunBulan08Kol = 2,
                            tahunBulan09 = "202303",
                            tahunBulan09Kol = 3,
                            tahunBulan10 = "202304",
                            tahunBulan10Kol = 1,
                            tahunBulan11 = "202305",
                            tahunBulan11Kol = 1,
                            tahunBulan12 = "202306",
                            tahunBulan12Kol = 1,
                            tahunBulan13 = "202307",
                            tahunBulan13Kol = 1,
                            tahunBulan14 = "202308",
                            tahunBulan14Kol = 1,
                            tahunBulan15 = "202309",
                            tahunBulan15Kol = 2,
                            tahunBulan16 = "202310",
                            tahunBulan16Kol = 2,
                            tahunBulan17 = "202311",
                            tahunBulan17Kol = 2,
                            tahunBulan18 = "202312",
                            tahunBulan18Kol = 3,
                            tahunBulan19 = "202401",
                            tahunBulan19Kol = 4,
                            tahunBulan20 = "202402",
                            tahunBulan20Kol = 1,
                            tahunBulan21 = "202403",
                            tahunBulan21Kol = 1,
                            tahunBulan22 = "202404",
                            tahunBulan22Kol = 1,
                            tahunBulan23 = "202405",
                            tahunBulan23Kol = 2,
                            tahunBulan24 = "202406",
                            tahunBulan24Kol = 2,
                            tahunbulan01ht = 0,
                            tahunbulan02ht = 0,
                            tahunbulan03ht = 0,
                            tahunbulan04ht = 0,
                            tahunbulan05ht = 0,
                            tahunbulan06ht = 0,
                            tahunbulan07ht = 31,
                            tahunbulan08ht = 61,
                            tahunbulan09ht = 91,
                            tahunbulan10ht = 0,
                            tahunbulan11ht = 0,
                            tahunbulan12ht = 0,
                            tahunbulan13ht = 0,
                            tahunbulan14ht = 0,
                            tahunbulan15ht = 5,
                            tahunbulan16ht = 35,
                            tahunbulan17ht = 66,
                            tahunbulan18ht = 96,
                            tahunbulan19ht = 127,
                            tahunbulan20ht = 0,
                            tahunbulan21ht = 0,
                            tahunbulan22ht = 0,
                            tahunbulan23ht = 4,
                            tahunbulan24ht = 34
                        },
                        new
                        {
                            jeniskredit = "X-30",
                            kreditno = 2,
                            Active = "N",
                            tahunBulan01 = "202207",
                            tahunBulan01Kol = 1,
                            tahunBulan02 = "202208",
                            tahunBulan02Kol = 2,
                            tahunBulan03 = "202209",
                            tahunBulan03Kol = 2,
                            tahunBulan04 = "202210",
                            tahunBulan04Kol = 2,
                            tahunBulan05 = "202211",
                            tahunBulan05Kol = 3,
                            tahunBulan06 = "202212",
                            tahunBulan06Kol = 4,
                            tahunBulan07 = "202301",
                            tahunBulan07Kol = 4,
                            tahunBulan08 = "202302",
                            tahunBulan08Kol = 5,
                            tahunBulan09 = "202303",
                            tahunBulan09Kol = 5,
                            tahunBulan10 = "202304",
                            tahunBulan10Kol = 5,
                            tahunBulan11 = "202305",
                            tahunBulan11Kol = 5,
                            tahunBulan12 = "202306",
                            tahunBulan12Kol = 5,
                            tahunBulan13 = "202307",
                            tahunBulan13Kol = 5,
                            tahunBulan14 = "202308",
                            tahunBulan14Kol = 5,
                            tahunBulan15 = "202309",
                            tahunBulan15Kol = 5,
                            tahunBulan16 = "202310",
                            tahunBulan16Kol = 5,
                            tahunBulan17 = "202311",
                            tahunBulan17Kol = 2,
                            tahunBulan18 = "202312",
                            tahunBulan18Kol = 5,
                            tahunBulan19 = "202401",
                            tahunBulan19Kol = 5,
                            tahunBulan20 = "202402",
                            tahunBulan20Kol = 5,
                            tahunBulan21 = "202403",
                            tahunBulan21Kol = 5,
                            tahunBulan22 = "202404",
                            tahunBulan22Kol = 5,
                            tahunBulan23 = "202405",
                            tahunBulan23Kol = 5,
                            tahunBulan24 = "202406",
                            tahunBulan24Kol = 5,
                            tahunbulan01ht = 0,
                            tahunbulan02ht = 30,
                            tahunbulan03ht = 60,
                            tahunbulan04ht = 90,
                            tahunbulan05ht = 120,
                            tahunbulan06ht = 150,
                            tahunbulan07ht = 180,
                            tahunbulan08ht = 210,
                            tahunbulan09ht = 240,
                            tahunbulan10ht = 270,
                            tahunbulan11ht = 300,
                            tahunbulan12ht = 330,
                            tahunbulan13ht = 360,
                            tahunbulan14ht = 390,
                            tahunbulan15ht = 420,
                            tahunbulan16ht = 450,
                            tahunbulan17ht = 480,
                            tahunbulan18ht = 510,
                            tahunbulan19ht = 540,
                            tahunbulan20ht = 570,
                            tahunbulan21ht = 600,
                            tahunbulan22ht = 630,
                            tahunbulan23ht = 660,
                            tahunbulan24ht = 690
                        },
                        new
                        {
                            jeniskredit = "P05",
                            kreditno = 3,
                            Active = "Y",
                            tahunBulan01 = "202207",
                            tahunBulan01Kol = 1,
                            tahunBulan02 = "202208",
                            tahunBulan02Kol = 2,
                            tahunBulan03 = "202209",
                            tahunBulan03Kol = 2,
                            tahunBulan04 = "202210",
                            tahunBulan04Kol = 2,
                            tahunBulan05 = "202211",
                            tahunBulan05Kol = 3,
                            tahunBulan06 = "202212",
                            tahunBulan06Kol = 1,
                            tahunBulan07 = "202301",
                            tahunBulan07Kol = 1,
                            tahunBulan08 = "202302",
                            tahunBulan08Kol = 1,
                            tahunBulan09 = "202303",
                            tahunBulan09Kol = 1,
                            tahunBulan10 = "202304",
                            tahunBulan10Kol = 1,
                            tahunBulan11 = "202305",
                            tahunBulan11Kol = 2,
                            tahunBulan12 = "202306",
                            tahunBulan12Kol = 2,
                            tahunBulan13 = "202307",
                            tahunBulan13Kol = 2,
                            tahunBulan14 = "202308",
                            tahunBulan14Kol = 3,
                            tahunBulan15 = "202309",
                            tahunBulan15Kol = 1,
                            tahunBulan16 = "202310",
                            tahunBulan16Kol = 1,
                            tahunBulan17 = "202311",
                            tahunBulan17Kol = 1,
                            tahunBulan18 = "202312",
                            tahunBulan18Kol = 2,
                            tahunBulan19 = "202401",
                            tahunBulan19Kol = 2,
                            tahunBulan20 = "202402",
                            tahunBulan20Kol = 1,
                            tahunBulan21 = "202403",
                            tahunBulan21Kol = 1,
                            tahunBulan22 = "202404",
                            tahunBulan22Kol = 1,
                            tahunBulan23 = "202405",
                            tahunBulan23Kol = 1,
                            tahunBulan24 = "202406",
                            tahunBulan24Kol = 1,
                            tahunbulan01ht = 0,
                            tahunbulan02ht = 5,
                            tahunbulan03ht = 35,
                            tahunbulan04ht = 65,
                            tahunbulan05ht = 95,
                            tahunbulan06ht = 0,
                            tahunbulan07ht = 0,
                            tahunbulan08ht = 0,
                            tahunbulan09ht = 0,
                            tahunbulan10ht = 0,
                            tahunbulan11ht = 7,
                            tahunbulan12ht = 37,
                            tahunbulan13ht = 67,
                            tahunbulan14ht = 97,
                            tahunbulan15ht = 0,
                            tahunbulan16ht = 0,
                            tahunbulan17ht = 0,
                            tahunbulan18ht = 1,
                            tahunbulan19ht = 31,
                            tahunbulan20ht = 0,
                            tahunbulan21ht = 0,
                            tahunbulan22ht = 0,
                            tahunbulan23ht = 0,
                            tahunbulan24ht = 0
                        });
                });

            modelBuilder.Entity("CIMBTest.Models.UseCase_02", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CIF")
                        .HasColumnType("int");

                    b.Property<int?>("DueDate")
                        .HasColumnType("int");

                    b.Property<int?>("FacilityStartDate")
                        .HasColumnType("int");

                    b.Property<string>("FacilityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Installment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MonthlyIncome")
                        .HasColumnType("int");

                    b.Property<int>("Outstanding")
                        .HasColumnType("int");

                    b.Property<decimal>("PercentageOfAnnualInterestRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Plafond")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Tenor")
                        .HasColumnType("int");

                    b.Property<string>("UsageType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Table_02");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CIF = 999999,
                            FacilityType = "Credit Card",
                            Installment = 800000m,
                            MonthlyIncome = 23000000,
                            Outstanding = 8000000,
                            PercentageOfAnnualInterestRate = 30.2m,
                            Plafond = 10000000,
                            Status = "Yes",
                            UsageType = "Consumption"
                        },
                        new
                        {
                            Id = 2,
                            CIF = 999999,
                            FacilityType = "Credit Card",
                            Installment = 75000m,
                            MonthlyIncome = 23000000,
                            Outstanding = 750000,
                            PercentageOfAnnualInterestRate = 30.2m,
                            Plafond = 5000000,
                            Status = "Yes",
                            UsageType = "Consumption"
                        },
                        new
                        {
                            Id = 3,
                            CIF = 999999,
                            DueDate = 45918,
                            FacilityStartDate = 44457,
                            FacilityType = "Personal Loan",
                            Installment = 439058.91m,
                            MonthlyIncome = 23000000,
                            Outstanding = 13000000,
                            PercentageOfAnnualInterestRate = 17.8m,
                            Plafond = 15000000,
                            Status = "Yes",
                            Tenor = 48,
                            UsageType = "Consumption"
                        },
                        new
                        {
                            Id = 4,
                            CIF = 999999,
                            DueDate = 47765,
                            FacilityStartDate = 42265,
                            FacilityType = "Mortgage",
                            Installment = 7364307.72m,
                            MonthlyIncome = 23000000,
                            Outstanding = 615000000,
                            PercentageOfAnnualInterestRate = 7.8m,
                            Plafond = 780000000,
                            Status = "Yes",
                            Tenor = 180,
                            UsageType = "Consumption"
                        });
                });

            modelBuilder.Entity("CIMBTest.Models.UseCase_03", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CIF")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MonthlyIncome")
                        .HasColumnType("int");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Table_03");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 45,
                            CIF = 8888888,
                            Gender = "Male",
                            MonthlyIncome = 23000000,
                            Occupation = "Employee"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
